//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drakesoft.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VersionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VersionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drakesoft.Resources.VersionResource", typeof(VersionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drakesoft LLC.
        /// </summary>
        internal static string _CurrentCompany {
            get {
                return ResourceManager.GetString("_CurrentCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Drakesoft.
        /// </summary>
        internal static string _CurrentCopyright {
            get {
                return ResourceManager.GetString("_CurrentCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.1.0.{0}.
        /// </summary>
        internal static string _CurrentFileVersion {
            get {
                return ResourceManager.GetString("_CurrentFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.1.0.
        /// </summary>
        internal static string _CurrentVersion {
            get {
                return ResourceManager.GetString("_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoConfig.
        /// </summary>
        internal static string Common_Common_Configuration {
            get {
                return ResourceManager.GetString("Common_Common_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drakesoft common.
        /// </summary>
        internal static string Common_Common_Description {
            get {
                return ResourceManager.GetString("Common_Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8c89eb9b-729c-441d-ba5a-10369f4da707.
        /// </summary>
        internal static string Common_Common_Guid {
            get {
                return ResourceManager.GetString("Common_Common_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string Common_Common_Product {
            get {
                return ResourceManager.GetString("Common_Common_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCommon.
        /// </summary>
        internal static string Common_Common_Title {
            get {
                return ResourceManager.GetString("Common_Common_Title", resourceCulture);
            }
        }
    }
}
